version = 0.1
[default.deploy.parameters]
stack_name = "operation-solidarity-users-domain"
resolve_s3 = true
s3_prefix = "operation-solidarity-users-domain"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
